### ISSUE TITLE
NPE for a very first load of properties files

### ISSUE THREAD

**Issue by LisyakovNikita** [heidelpay/heidelpayJava#100]
Hi,

PropertiesUtil::loadProperties will throw NPE on the very first PropertiesUtil::getString call. It's trying to find a non-existed file inside the jar. Please find a screenshot attached.
![Screenshot from 2020-11-13 10-56-08](https://user-images.githubusercontent.com/43514829/99053479-a6015680-25a1-11eb-8260-1eed30f9b96c.png)

**Comment by LisyakovNikita** [comment]
The version we are using is 1.11.2.0.

**Comment by McIntozh** [comment]
With Version 1.11.2.1 the code is replaced by
```
  this.properties.put(PUBLIC_KEY1, System.getProperty(PUBLIC_KEY1));
  this.properties.put(PRIVATE_KEY1, System.getProperty(PRIVATE_KEY1));
  this.properties.put(PRIVATE_KEY2, System.getProperty(PRIVATE_KEY2));
  this.properties.put(PRIVATE_KEY3, System.getProperty(PRIVATE_KEY3));
  this.properties.put(MARKETPLACE_PRIVATE_KEY, System.getProperty(MARKETPLACE_PRIVATE_KEY));
```
Which also throws a NullPointerException, due to the fact that the Map in Properties does not permit null values.
These system properties are only needed for the unit tests and will never be set or used in production.

**Comment by DerAusHeidelberg** [comment]
Hi @LisyakovNikita @McIntozh,

we are currently on it and plan to release in the near future.

Please be a little patient. We will inform you about the new release when its done.

**Comment by DerAusHeidelberg** [comment]
Hi @LisyakovNikita @McIntozh,

we have now released a Fix for this Issue.

Please see https://search.maven.org/artifact/com.heidelpay.payment/heidelpayJava/1.11.2.2/jar

Thank you for helping us to improve.
I will now close this Issue.
