### ISSUE TITLE
Maven NullPointerException - rework passing properties (keys) on command line

### ISSUE THREAD

**Issue by MojoManagement** [heidelpay/heidelpayJava#81]
Since 32dcfa9e312c31097d377b3dba3577c7cd87c5b5 it is not even possible to trigger any maven run without defining all keys in command line.
Passing keys as properties should be optional, not mandatory.

Properties in pom:
> 
		<publickey1>${publickey1}</publickey1>
		<privatekey1>${privatekey1}</privatekey1>
		<privatekey2>${privatekey2}</privatekey2>
		<privatekey3>${privatekey3}</privatekey3>

Exception:
> [INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.691 s
[INFO] Finished at: 2020-07-20T20:02:56+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] NullPointerException
java.lang.NullPointerException
    at java.util.concurrent.ConcurrentHashMap$MapEntry.setValue (ConcurrentHashMap.java:3546)
    at org.apache.maven.model.interpolation.StringVisitorModelInterpolator$ModelVisitor.visit 
    ...
    ...
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)

**Comment by DerAusHeidelberg** [comment]
Hi @MojoManagement ,

we have now released a Fix for this Issue in Version 1.11.2.2.

Please see https://search.maven.org/artifact/com.heidelpay.payment/heidelpayJava/1.11.2.2/jar

Thank you for helping us to improve.
I will now close this Issue.
